CREATE TABLE usuarios (
                          id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre         VARCHAR2(255)  NOT NULL,
                          email          VARCHAR2(255)  NOT NULL UNIQUE,
                          password       VARCHAR2(255)  NOT NULL,
                          fecha_registro TIMESTAMP,
                          activo         NUMBER(1)      DEFAULT 0 NOT NULL,
                          rol            VARCHAR2(50)   NOT NULL,
                          ultimo_acceso  TIMESTAMP
);