CREATE TABLE verification_token (
                                    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    token             VARCHAR2(255),
                                    usuario_id        NUMBER NOT NULL,
                                    fecha_expiracion  TIMESTAMP,
                                    CONSTRAINT fk_vertoken_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);