CREATE TABLE password_reset_tokens (
                                       id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       token             VARCHAR2(255),
                                       usuario_id        NUMBER,
                                       fecha_expiracion  TIMESTAMP,
                                       CONSTRAINT fk_pwdreset_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);