CREATE TABLE recuerdos (
                           id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           texto       VARCHAR2(2000) NOT NULL,
                           fecha       TIMESTAMP      NOT NULL,
                           imagen      VARCHAR2(255),
                           visibilidad VARCHAR2(20)   DEFAULT 'PRIVADO' NOT NULL,
                           usuario_id  NUMBER,
                           CONSTRAINT fk_recuerdo_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);