spring.application.name=maryNotebook

spring.datasource.url=jdbc:oracle:thin:@maubz05ckgsd23uw_high?TNS_ADMIN=/app/wallet
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

file.upload-dir=${FILE_UPLOAD_DIR:/uploads}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

maubz05ckgsd23uw_high = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.eu-madrid-3.oraclecloud.com))(connect_data=(service_name=g7436484ab8b922_maubz05ckgsd23uw_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))


spring.mail.host=smtp.serviciodecorreo.es
spring.mail.port=465
spring.mail.username=marymemories@marymemories.es
spring.mail.password=*Quieroser*12*

# Protocolo y Autenticación
spring.mail.properties.mail.smtp.auth=true

# Configuración para SSL (Puerto 465)
# A diferencia de Gmail/587, aquí usamos SSL directo
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

# Seguridad y Trust
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.serviciodecorreo.es

# Timeouts de red
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000